In [5]:
import numpy as np # 04/01/2023

# why nupy?

In [3]:
a= [1,2,3,4,5]
[i*2 for i in a]

[2, 4, 6, 8, 10]

##### we can say element wise operation

In [4]:
a_np = np.array([1,2,3,4,5])
print(a_np)

[1 2 3 4 5]


In [5]:
a_np*2

array([ 2,  4,  6,  8, 10])

In [6]:
l = range(100000)

In [9]:
%timeit [i*2 for i in l] #it is magic method;

11.8 ms ± 104 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
l_np = np.array(range(100000))
%timeit l_np * 2

46.5 µs ± 1.44 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [7]:
np.array([1,2,3])

array([1, 2, 3])

In [8]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [9]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [10]:
range(1,10,2.5)

TypeError: 'float' object cannot be interpreted as an integer

In [12]:
np.arange(1,10,2.5)

array([1. , 3.5, 6. , 8.5])

In [13]:
#np.range()
#np.linspace()..very important.....>POST-ready    # how to learn yourself.

In [14]:
type(l_np)

numpy.ndarray

In [15]:
l_np = np.array([1,2,3])

In [16]:
l_np.ndim

1

In [17]:
l_np.shape

(3,)

In [26]:
l_np_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
l_np_2.ndim

2

In [25]:
l_np_2.shape

(3, 3)

In [28]:
# Numpy - C code runing in background

In [29]:
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10,-8])
x[(x >= -5) & (x <= 15)] *= -1 