# NUMPY DAY1

In [1]:
import numpy as np

# what is nupy?

# > Numpy is module for python. the name is an acronym for numerical python. it is an extenssion module of python, mostly writen in c. This make sure that the pre-compiled mathematical and numerical function and functionality of Num-Py grantee grear excution speed.

# Core python vs NumPy

# < Python 1.1 High level number object: integers, floating point. 1.2 Container:- List with cheap insertion and append method ,  dictionary with fast lookup. 


# >NumPy 2.1 Array oriented computing 2.2 Efficiently implemented array 2.3 design for scientific computation.

In [3]:
# why numpy 
a =  [1,2,3,4,5]

In [4]:
a =  [1,2,3,4,5]
[i*2 for i in a]

[2, 4, 6, 8, 10]

In [8]:
a_np = np.array([1,2,3,4,5])
print(a_np)

[1 2 3 4 5]


In [9]:
a*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [10]:
a_np * 2

array([ 2,  4,  6,  8, 10])

In [22]:
l = range(20)

In [23]:
[i*2 for i in l]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]

In [16]:
%timeit [i*2 for i in l]

8.88 µs ± 33.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [17]:
l_np = np.array(range(100))
%timeit l_np * 2

1.82 µs ± 24.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# how to create numpy array


In [18]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [20]:
np.arange(1,5)

array([1, 2, 3, 4])

In [21]:
np.arange(1,21,3)

array([ 1,  4,  7, 10, 13, 16, 19])

# why using in numpy range vs arange.>

In [31]:
range(1,10,2.5)

TypeError: 'float' object cannot be interpreted as an integer

In [33]:
np.arange(1,10,2.5)

array([1. , 3.5, 6. , 8.5])

In [34]:
# np.arange()
# np.linspace()---> Post-ready, important

In [35]:
type(l_np)

numpy.ndarray

In [36]:
l_np = np.array([1,2,3,4,5])

In [38]:
l_np.ndim

1

In [39]:
l_np.shape

(5,)

In [40]:
l_np_2 = np.array([[1,2],[3,4],[4,5]])

In [41]:
l_np_2.ndim

2

In [42]:
l_np_2.shape

(3, 2)

In [44]:
np.array([1,2,3,4,]).dtype

dtype('int32')

In [46]:
np.array([1,2,3,4.5])   #all the number were typecasted to float

array([1. , 2. , 3. , 4.5])

In [47]:
np.array([True,1,2,3,4.5]).dtype

dtype('float64')

In [49]:
np.array([True,1,2,3,4.5,"sanjeev"])    #nupy have hmogenious (data)array

array(['True', '1', '2', '3', '4.5', 'sanjeev'], dtype='<U32')

# Indexing and slicing

In [54]:
m1 = np.arange(1,14)
m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [55]:
m1[0]

1

In [56]:
m1[-1]

13

In [57]:
m1[:5]

array([1, 2, 3, 4, 5])

In [58]:
m1 = np.array([100,200,300,400,500,600])
m1

array([100, 200, 300, 400, 500, 600])

In [59]:
m1[[2,5]]

array([300, 600])

In [60]:
m1[[2,5,2]]   # notice that multiple indexes are provided at list [[]] , m1[2,5,2] ??

array([300, 600, 300])

In [61]:
m1 = np.array([1,2,3,4,5,6,7,8,9,10])
m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
m1[:5]

array([1, 2, 3, 4, 5])

In [63]:
m1[-5:-1]

array([6, 7, 8, 9])

# Fancy indexing

In [65]:
m1 = np.array([1,2,3,4,5,6,7,8,9,10])
m1<6

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [66]:
m1[m1<7] #Fancy indexing , Boolean indexing,boolean masking

array([1, 2, 3, 4, 5, 6])

In [67]:
m1 % 2 == 0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [68]:
m1[m1%2 == 0]

array([ 2,  4,  6,  8, 10])

In [69]:
m1[(m1%2==0) | (m1%5==0)]

array([ 2,  4,  5,  6,  8, 10])

In [70]:
m1[(m1%2==0) & (m1%5==0)]

array([10])

In [71]:
#put multip[le condition in bracket
#  or --> | for and --> &

In [72]:
np.arange(4) + 3

array([3, 4, 5, 6])

In [77]:
a = np.array([1,2,3]) # element wise Operation
b = np.array([4,5,6])
a + b

array([5, 7, 9])

In [78]:
a = np.array([1,2,3,10])    # the shape 2 nupy array have to be same
b = np.array([4,5,6])
a + b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [79]:
a = np.array([1,2,3,4,5])


In [80]:
np.sum(a)

15

In [81]:
np.mean(a)

3.0

In [82]:
np.min(a)

1

In [84]:
np.max(a)

5

In [86]:
a = np.array([1,2,3,4,5])

In [87]:
np.max(a)

5

In [88]:
np.argmax(a)

4

In [89]:
np.argmin(a)

0

In [90]:
np.argmax([1,2,3,4,5,5,5])

4